name: Build & Update Promtmix

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "12 3 * * *"  # daily UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install jinja2
      - name: Build site
        run: |
          python src/build.py
      - name: Commit built site
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff-index --quiet HEAD || git commit -m "build: update site [skip ci]"
          git push
